; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
lib_deps = mikalhart/TinyGPSPlus@^1.1.0 ; Adiciona a biblioteca <TinyGPS++.h>
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200 ; Força o monitor a operar em 115200 baud rate
monitor_port = /dev/ttyACM0 ; Força o monitor olhar essa porta (Desativar ou mudar essa flag em outros PCs)

build_flags = 
    -DARDUINO_USB_MODE=1 ; Não entendi o motivo dessa flag, mas sem ela não funciona
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Sem essa flag "Serial.print()", é enviado para as portas 20 e 21 da esp
